# 通用数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ysmanagement?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123580

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
